routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('cache', function() {
    Artisan::call('config:cache');
    Artisan::call('route:clear');
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('view:clear');
    return '<h1>Ok !</h1>';
});

Route::get('install', function() {
    Artisan::call('migrate');
    Artisan::call('db:seed');
    return '<h1>Ok !</h1>';
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'],function (){
    Route::get('/login', 'Auth\AdminsLoginController@showForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminsLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminsLoginController@logout')->name('admin.logout');
    Route::group(['middleware' => 'auth:admin'] ,function (){
        Route::get('/', 'AdminsController@index')->name('admin.dashboard');
        Route::resource('clients', 'Admin\ClientsController');
        Route::post('appointment/getMonthsDays', 'Admin\AppointmentsController@getMonthsDays');
        Route::resource('appointment', 'Admin\AppointmentsController');
        //Route::resource('waiting', 'Admin\WaitingController');
        Route::get('settings', 'Admin\GeneralSettingsController@index')->name('admin.settings');
        Route::patch('settings', 'Admin\GeneralSettingsController@store');
        //ProfileController
        Route::post('setAsPresentRDV','CalendarsController@setAsPresentRDV')->name('present');
        Route::post('deleteRDV','CalendarsController@softDeleteRDV')->name('deleteRDV');
        Route::get('profile/edit-profile','ProfileController@index')->name('admin.profile.index');
        Route::post('profile/edit-profile', 'ProfileController@index')->name('admin.profile.index');
        Route::get('profile/change-password', 'ProfileController@password')->name('admin.profile.password');
        Route::post('profile/change-password', 'ProfileController@password')->name('admin.profile.password');
        // UploadController
        Route::post('upload', 'UploadController@index')->name('admin.upload');
    });

});
Route::resource('calendar', 'CalendarsController');
Route::group(['middleware' => 'auth'] , function() {
    //ProfileController
    Route::get('profile/edit-profile','ProfileController@index')->name('profile.index');
    Route::post('profile/edit-profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/change-password', 'ProfileController@password')->name('profile.password');
    Route::post('profile/change-password', 'ProfileController@password')->name('profile.password');
    // UploadController
    Route::post('upload', 'UploadController@index')->name('upload');
    //CalendarsController
   // Route::resource('calendar', 'CalendarsController');
   Route::post('proposerdv','CalendarsController@proposeRdv')->name('propose');
   Route::post('annulerRDV','CalendarsController@deleteRDV')->name('annulerRDV');
  // Route::get('proposerdv','CalendarsController@proposeRdv')->name('propose');
});

app/Appointment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $guarded = [];

    public function monthsOptions()
    {
        return [
            '01' => 'Janvier',
            '02' => 'Février',
            '03' => 'Mars',
            '04' => 'Avril',
            '05' => 'Mai',
            '06' => 'Juin',
            '07' => 'Juillet',
            '08' => 'Août',
            '09' => 'Septembre',
            '10' => 'Octobre',
            '11' => 'Novembre',
            '12' => 'Décembre',
        ];

    }

    public function daysOptions(){
        return [
            '01' => 'Dimanche',
            '02' => 'Lundi',
            '03' => 'Mardi',
            '04' => 'Mercredi',
            '05' => 'Jeudi',
            '06' => 'Vendredi',
            '07' => 'Samedi'
        ];
    }

    /**
     * @inheritDoc
     */
    public function resolveChildRouteBinding($childType, $value, $field)
    {
        // TODO: Implement resolveChildRouteBinding() method.
    }
}

app/Http/Controllers/Admin/AppointmentsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Appointment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AppointmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $num = 1;
        $appointments = Appointment::all();
        return view('admin.appointments.index', compact('appointments', 'num'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $appointment = new Appointment();
        return view('admin.appointments.create', compact('appointment'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $pre_data = $request;
        if($pre_data['type'] == 'fixed'){
            $data['type'] = 'fixed';

            if(isset($pre_data['fixed_label'])){
                $data['label'] = $pre_data['fixed_label'];
            }
            if(isset($pre_data['fixed_months'])){
                $data['months'] = json_encode($pre_data['fixed_months']);
            }
            if(isset($pre_data['fixed_days'])){
                $data['days'] = json_encode($pre_data['fixed_days']);
            }
            if(isset($pre_data['fixed_work_start'])){
                $data['time'] = json_encode($pre_data['fixed_work_start']. '=>'.$pre_data['fixed_work_end'] );
            }
            $data['all_day'] = $pre_data['all_day'];
            $data['custom_hvolume'] = $pre_data['custom_hvolume'];
        }else{
            $data['type'] = 'custom';
            if(isset($pre_data['custom_label'])){
                $data['label'] = $pre_data['custom_label'];
            }
            for ($i=1; $i <= $request['rows_num']; $i++){

                if(isset($pre_data['custom_months_'. $i])){
                    $data['months'][$i] = $pre_data['custom_months_'. $i];
                }
                if(isset($pre_data['custom_days_'. $i])){
                    $data['days'][$i] = $pre_data['custom_days_'. $i];
                }

                if(isset($pre_data['custom_work_start_'. $i])){
                    $data['time'][$i] = $pre_data['custom_work_start_'. $i]. '=>'.$pre_data['custom_work_end_'. $i];
                }

                if(isset($pre_data['custom_hvolume_'. $i])){
                    $data['custom_hvolume'][$i] = $pre_data['custom_hvolume_'. $i];
                }
            }

            $data['months'] = json_encode($data['months']);
            $data['days'] = json_encode($data['days']);
            $data['time'] = json_encode($data['time']);
            $data['custom_hvolume'] = json_encode($data['custom_hvolume']);
        }

        Appointment::create($data);
        return redirect('admin/appointment');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Appointment  $appointment
     * @return \Illuminate\Http\Response
     */
    public function show(Appointment $appointment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Appointment  $appointment
     * @return \Illuminate\Http\Response
     */
    public function edit(Appointment $appointment)
    {
        return view('admin.appointments.edit', compact('appointment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Appointment  $appointment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Appointment $appointment)
    {

        $pre_data = $request;
        $data['label'] = $pre_data['label'];
        if($pre_data['type'] == 'fixed'){
            $data['type'] = 'fixed';
            if(isset($pre_data['fixed_months'])){
                $data['months'] = json_encode($pre_data['fixed_months']);
            }
            if(isset($pre_data['fixed_days'])){
                $data['days'] = json_encode($pre_data['fixed_days']);
            }
            if(isset($pre_data['fixed_work_start'])){
                $data['time'] = json_encode($pre_data['fixed_work_start']. '=>'.$pre_data['fixed_work_end'] );
            }
            $data['all_day'] = $pre_data['all_day'];
            $data['custom_hvolume'] = $pre_data['custom_hvolume'];
        }else{
            $data['type'] = 'custom';
            for ($i=1; $i <= $request['rows_num']; $i++){

                if(isset($pre_data['custom_months_'. $i])){
                    $data['months'][$i] = $pre_data['custom_months_'. $i];
                }
                if(isset($pre_data['custom_days_'. $i])){
                    $data['days'][$i] = $pre_data['custom_days_'. $i];
                }

                if(isset($pre_data['custom_work_start_'. $i])){
                    $data['time'][$i] = $pre_data['custom_work_start_'. $i]. '=>'.$pre_data['custom_work_end_'. $i];
                }
                if(isset($pre_data['custom_hvolume_'. $i])){
                    $data['custom_hvolume'][$i] = $pre_data['custom_hvolume_'. $i];
                }
            }

            $data['months'] = json_encode($data['months']);
            $data['days'] = json_encode($data['days']);
            $data['time'] = json_encode($data['time']);
            $data['custom_hvolume'] = json_encode($data['custom_hvolume']);
        }

        $appointment->update($data);
        return redirect('admin/appointment');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Appointment  $appointment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Appointment $appointment)
    {
        //
    }

    public function enableAppointment(Request $request, Appointment $appointment)
    {
        $data['is_active'] = $request['is_active'];
        $appointment->update($data);
        return redirect('/admin/appointment');
    }

    public function getMonthsDays(Request $request){
        if ($request->ajax()){

            $appointment = new Appointment();
            $data['months'] = $appointment->monthsOptions();
            $data['days'] = $appointment->daysOptions();

            return response()->json($data);
        }
    }

    private function validateRequest()
    {
        return request()->validate(
            [
                'label' => 'required',
                'type' => 'required',
                'fixed_days' => 'nullable',
                'custom_days_*' => 'nullable',
                'fixed_months' => 'nullable',
                'custom_months-*' => 'nullable',
                'fixed_work_start' => 'nullable',
                'custom_work_start' => 'nullable',
                'fixed_work_end' => 'nullable',
                'custom_work_end_*' => 'nullable',
                'all_day' => 'nullable',
                'rows_num' => 'nullable',
                'custom_hvolume' => 'nullable',
            ],
            [
                'label.required' => 'Vous devez entrer un label',
                'type.required' => 'Vous devez selectionner un type',
            ]
        );
    }



}

resources/views/admin/appointments/create.blade.php
@extends('layouts.index', ['title' => 'Ajouter plage', 'class' => 'pg-title bg-gradient-danger' ])

@section('content')
    {!! Form::open(['method' => 'POST', 'action' => 'Admin\AppointmentsController@store']) !!}
    @include('admin.appointments.form')
    {!! Form::close() !!}


@endsection

resources/views/admin/appointments/edit-form.blade.php
<input type="hidden" name="type" value="{{($appointment->type == 'fixed')? 'fixed' : 'custom'}}">
@if($appointment->type == 'fixed')
<div>
    <div class="form-group">
        {!! Form::label('label', 'Label:') !!}
        <input type="text" name="label" class="form-control {{$errors->has('label') ? 'is-invalid':''}}" value="{{isset($appointment->label) ? $appointment->label : '' }}">
        <span class="invalid-feedback">{{$errors->first('label')}}</span>
    </div>
    <div class="form-group">
        <label for="">Les mois</label>
        <div class="row">
            @foreach($appointment->monthsOptions() as $key => $month)
                <div class="col-3">
                    <input type="checkbox" name="fixed_months[]" value="{{$key}}" @if(!empty($appointment->months) && in_array($key, (array)json_decode($appointment->months))) checked @endif> {{ $month }}
                </div>
            @endforeach
        </div>
    </div>

    <div class="form-group">
        <label for="">Les jours</label>
        <div class="row">
            @foreach($appointment->daysOptions() as $key => $day)
                <div class="col-3">
                    <input type="checkbox" name="fixed_days[]" value="{{$key}}" @if(!empty($appointment->days) && in_array($key, (array)json_decode($appointment->days))) checked @endif > {{ $day }}
                </div>
            @endforeach
        </div>

    </div>
    <div class="form-group">
        <input type="radio" name="all_day" value="true" {{($appointment->all_day == 'true')? 'checked' : ''}}> Toute la journée
        <input type="radio" name="all_day" value="false" {{($appointment->all_day == 'false')? 'checked' : ''}}> Pesonaliser
    </div>
    @if($appointment->time)
        @php
            $time = explode('=>', json_decode($appointment->time));
            $start = $time[0];
            $end = $time[1];
        @endphp
    @endif
    <div class="form-group">
        {!! Form::label('fixed_work_start', 'Heure de debut:') !!}
        <input type="text" name="fixed_work_start" class="form-control {{$errors->has('fixed_work_start') ? 'is-invalid':''}}" value="{{isset($start) ? $start : '' }}">
        <span class="invalid-feedback">{{$errors->first('fixed_work_start')}}</span>
    </div>
    <div class="form-group">
        {!! Form::label('fixed_work_end', 'Heure de fin:') !!}
        <input type="text" name="fixed_work_end" class="form-control {{$errors->has('fixed_work_end') ? 'is-invalid':''}}" value="{{isset($end) ? $end : '' }}">
        <span class="invalid-feedback">{{$errors->first('fixed_work_end')}}</span>
    </div>
    <input type="radio" {{isset($appointment->custom_hvolume) ? 'checked' : '' }}> Volume Pesonaliser?
    <div class="form-group">
        {!! Form::label('custom_hvolume', 'Volume horaire:') !!}
        <input type="text" name="custom_hvolume" class="form-control {{$errors->has('custom_hvolume') ? 'is-invalid':''}}" value="{{isset($appointment->custom_hvolume) ? $appointment->custom_hvolume : '' }}">
        <span class="invalid-feedback">{{$errors->first('custom_hvolume')}}</span>
    </div>
</div>
@endif

@if($appointment->type == 'custom')
<div>

    <div class="form-group">
        {!! Form::label('label', 'Label:') !!}
        <input type="text" name="label" class="form-control {{$errors->has('label') ? 'is-invalid':''}}" value="{{isset($appointment->label) ? $appointment->label : '' }}">
        <span class="invalid-feedback">{{$errors->first('label')}}</span>
    </div>

    @php
        $rows_num = count((array)json_decode($appointment->months));
        $months = (array)json_decode($appointment->months);
        $days = (array)json_decode($appointment->days);
        $time = (array)json_decode($appointment->time);
        $custom_hvolume = (array)json_decode($appointment->custom_hvolume);
    @endphp

    @for($i=1; $i <= $rows_num; $i++)
    <div class="row custom-row">
        <div class="col-3">
            <select name="custom_months_{{$i}}[]" class="form-control select-js" multiple>
                @foreach($appointment->monthsOptions() as $key => $month)
                    @foreach($months[$i] as $k => $m)
                        @if($m == $key) <option value="{{$m}}" selected>{{$appointment->monthsOptions()[$m]}}</option>  @break @endif
                    @endforeach
                    <option value="{{$key}}">{{$month}}</option>
                @endforeach
            </select>
        </div>
        <div class="col-3">
            <select name="custom_days_{{$i}}[]" class="form-control select-js" multiple>
                @foreach($appointment->daysOptions() as $key => $day)
                    @foreach($days[$i] as $k => $d)
                        @if($d == $key) <option value="{{$d}}" selected>{{$appointment->daysOptions()[$d]}}</option>  @break @endif
                    @endforeach
                    <option value="{{$key}}">{{$day}}</option>
                @endforeach
            </select>
        </div>
        <div class="col-3">
            <div class="row">
                @php
                        $custom_time = explode('=>', $time[$i]);
                        $start = $custom_time[0];
                        $end = $custom_time[1];

                @endphp
                <div class="col-6">
                    <input type="text" name="custom_work_start_{{$i}}" class="form-control {{$errors->has('custom_work_start') ? 'is-invalid':''}}" value="{{isset($start) ? $start : '' }}">                    <span class="invalid-feedback">{{$errors->first('custom_work_start')}}</span>
                </div>
                <div class="col-6">
                    <input type="text" name="custom_work_end_{{$i}}" class="form-control {{$errors->has('fixed_work_end') ? 'is-invalid':''}}" value="{{isset($end) ? $end : '' }}">
                    <span class="invalid-feedback">{{$errors->first('custom_work_end')}}</span>
                </div>
            </div>
        </div>
        <div class="col-2">
            <input type="text" name="custom_hvolume_{{$i}}" class="form-control {{$errors->has('custom_hvolume') ? 'is-invalid':''}}" placeholder="volume horaire" value="{{isset($custom_hvolume[$i]) ? $custom_hvolume[$i] : '' }}">
            <span class="invalid-feedback">{{$errors->first('custom_hvolume')}}</span>
        </div>
        @if($rows_num - $i ==0)
        <div class="col-1">
            <button id="addRow" type="button" class="btn btn-sm btn-success">+</button>
        </div>
        @else
            <div class="col-1">
                <button id="removeRow" type="button" class="btn btn-sm btn-danger">-</button>
            </div>
        @endif
    </div>
    @endfor

    <div><input type="hidden" class="rows-num" name="rows_num" value="{{$rows_num}}"></div>
</div>

@endif

<div class="form-group">
    {!! Form::submit('أضف', ['class'=>'btn btn-primary']) !!}
</div>

resources/views/admin/appointments/edit.blade.php
@extends('layouts.index', ['title' => 'Modifier plage', 'class' => 'pg-title bg-gradient-danger' ])

@section('content')
    {!! Form::model($appointment, ['method' => 'PATCH', 'action' => ['Admin\AppointmentsController@update', $appointment->id]]) !!}
    @include('admin.appointments.edit-form')
    {!! Form::close() !!}


@endsection

resources/views/admin/appointments/form.blade.php
<div class="form-group">
    <input type="checkbox" name="type" value="fixed" > Fixe
    <input type="checkbox" name="type" value="custom"> Personaliser
</div>

<div>
    <div class="form-group">
        {!! Form::label('fixed_label', 'Label:') !!}
        <input type="text" name="fixed_label" class="form-control {{$errors->has('fixed_label') ? 'is-invalid':''}}">
        <span class="invalid-feedback">{{$errors->first('fixed_label')}}</span>
    </div>
    <div class="form-group">
        <label for="">Les mois</label>
        <div class="row">
            @foreach($appointment->monthsOptions() as $key => $month)
                <div class="col-3">
                    <input type="checkbox" name="fixed_months[]" value="{{$key}}"> {{ $month }}
                </div>
            @endforeach
        </div>
    </div>

    <div class="form-group">
        <label for="">Les jours</label>
        <div class="row">
            @foreach($appointment->daysOptions() as $key => $day)
                <div class="col-3">
                    <input type="checkbox" name="fixed_days[]" value="{{$key}}" @if(!empty($appointment->days) && in_array($key, (array)json_decode($appointment->days))) checked @endif > {{ $day }}
                </div>
            @endforeach
        </div>

    </div>
    <div class="form-group">
        <input type="radio" name="all_day" value="true"> Toute la journée
        <input type="radio" name="all_day" value="false"> Pesonaliser
    </div>

    <div class="form-group">
        {!! Form::label('fixed_work_start', 'Heure de debut:') !!}
        <input type="text" name="fixed_work_start" class="form-control {{$errors->has('fixed_work_start') ? 'is-invalid':''}}">
        <span class="invalid-feedback">{{$errors->first('fixed_work_start')}}</span>
    </div>
    <div class="form-group">
        {!! Form::label('fixed_work_end', 'Heure de fin:') !!}
        <input type="text" name="fixed_work_end" class="form-control {{$errors->has('fixed_work_end') ? 'is-invalid':''}}">
        <span class="invalid-feedback">{{$errors->first('fixed_work_end')}}</span>
    </div>

    <input type="radio"> Volume Pesonaliser?
    <div class="form-group">
        {!! Form::label('custom_hvolume', 'Volume horaire:') !!}
        <input type="text" name="custom_hvolume" class="form-control {{$errors->has('custom_hvolume') ? 'is-invalid':''}}">
        <span class="invalid-feedback">{{$errors->first('custom_hvolume')}}</span>
    </div>
</div>


<hr>

<div>
    <div class="form-group">
        {!! Form::label('custom_label', 'Label:') !!}
        <input type="text" name="custom_label" class="form-control {{$errors->has('custom_label') ? 'is-invalid':''}}">
        <span class="invalid-feedback">{{$errors->first('custom_label')}}</span>
    </div>

    <div class="row custom-row">
        <div class="col-3">
            <select name="custom_months_1[]" class="form-control select-js" multiple>
                @foreach($appointment->monthsOptions() as $key => $month)
                    <option value="{{$key}}">{{$month}}</option>
                @endforeach
            </select>
        </div>
        <div class="col-3">
            <select name="custom_days_1[]" class="form-control select-js" multiple>
                @foreach($appointment->daysOptions() as $key => $day)
                    <option value="{{$key}}">{{$day}}</option>
                @endforeach
            </select>
        </div>
        <div class="col-3">
            <div class="row">
                <div class="col-6">
                    {!! Form::text('custom_work_start_1', old('custom_work_start'), ['class'=>'form-control '.($errors->has('custom_work_start') ? 'is-invalid':''), 'placeholder' => 'Heure de début']) !!}
                    <span class="invalid-feedback">{{$errors->first('custom_work_start')}}</span>
                </div>
                <div class="col-6">
                    {!! Form::text('custom_work_end_1', old('custom_work_end'), ['class'=>'form-control '.($errors->has('custom_work_end') ? 'is-invalid':''), 'placeholder' => 'Heure de fin']) !!}
                    <span class="invalid-feedback">{{$errors->first('custom_work_end')}}</span>
                </div>
            </div>
        </div>
        <div class="col-2">
            <input type="text" name="custom_hvolume_1" class="form-control {{$errors->has('custom_hvolume') ? 'is-invalid':''}}" placeholder="volume horaire">
            <span class="invalid-feedback">{{$errors->first('custom_hvolume')}}</span>
        </div>
        <div class="col-1">
            <button id="addRow" type="button" class="btn btn-sm btn-success">+</button>
        </div>
    </div>

    <div><input type="hidden" class="rows-num" name="rows_num" value="1"></div>
</div>



<div class="form-group">
    {!! Form::submit('أضف', ['class'=>'btn btn-primary']) !!}
</div>

resources/views/admin/appointments/index.blade.php
@extends('layouts.index', ['title' => 'Plages', 'class' => 'pg-title bg-gradient-danger' ])

@section('content')
    <div class="link-add-box">
        <a href="{{route('appointment.create')}}" class="btn btn-gradient-primary">Ajouter nouvelle plage</a>
    </div>
    <table id="myTable" class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">label</th>
            <th scope="col">type</th>
            <th scope="col">Mois</th>
            <th scope="col">عمليات</th>
        </tr>
        </thead>
        <tbody>
        @foreach($appointments as $appointment)
            <tr>
                <th scope="row">{{$num++}}</th>
                <td>{{$appointment->label}}</td>
                <td>{{$appointment->type == 'fixed' ? 'fixe' : 'personaliser'}}</td>
                <td>
                    @if($appointment->type == 'fixed')
                        @foreach(json_decode($appointment->months) as $month)
                            {{$appointment->monthsOptions()[$month]}}
                        @endforeach
                    @else
                        @php
                            $data_months = (array)json_decode($appointment->months);
                            $data_days = (array)json_decode($appointment->days);
                            $data_time = (array)json_decode($appointment->time);

                        @endphp
                        @for($i=1; $i<=count($data_months); $i++)
                            @for($j=0; $j< count($data_months[$i]); $j++)
                                {{ isset($data_months[$i][$j]) ? $appointment->monthsOptions()[$data_months[$i][$j]] : ' ' }}
                                {{isset($data_days[$i][$j]) ? $appointment->daysOptions()[$data_days[$i][$j]] : ' ' }}
                                {{ $data_time[$i] }}
                                {!! '<br>' !!}
                            @endfor
                        @endfor
                    @endif
                </td>
                <td class="dropdown">
                    <a href="#" class="delete btn btn-sm btn-danger" data-id="{{$appointment->id}}" data-url="{{route('appointment.destroy', $appointment->id)}}" data-success="تم حذف الفئة بنجاح!" >Supprimer</a>
                    <a href="{{route('appointment.edit', $appointment->id)}}" class="btn btn-sm btn-success">Modifier</a>
                    @if($appointment->is_active == 1)
                        <a href="{{route('appointment.edit', $appointment->id)}}" class="btn btn-sm btn-dark">reactiver</a>
                    @else
                        <a href="{{route('appointment.edit', $appointment->id)}}" class="btn btn-sm btn-secondary">désactiver</a>
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection