routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('cache', function() {
    Artisan::call('config:cache');
    Artisan::call('route:clear');
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('view:clear');
    return '<h1>Ok !</h1>';
});

Route::get('install', function() {
    Artisan::call('migrate');
    Artisan::call('db:seed');
    return '<h1>Ok !</h1>';
});

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'],function (){
    Route::get('/login', 'Auth\AdminsLoginController@showForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminsLoginController@login')->name('admin.login.submit');
    Route::post('/logout', 'Auth\AdminsLoginController@logout')->name('admin.logout');
    Route::group(['middleware' => 'auth:admin'] ,function (){
        Route::get('/', 'AdminsController@index')->name('admin.dashboard');
        Route::resource('clients', 'Admin\ClientsController');
        Route::post('appointment/getMonthsDays', 'Admin\AppointmentsController@getMonthsDays');
        Route::resource('appointment', 'Admin\AppointmentsController');
        //Route::resource('waiting', 'Admin\WaitingController');
        Route::get('settings', 'Admin\GeneralSettingsController@index')->name('admin.settings');
        Route::patch('settings', 'Admin\GeneralSettingsController@store');
        //ProfileController
        Route::post('setAsPresentRDV','CalendarsController@setAsPresentRDV')->name('present');
        Route::post('deleteRDV','CalendarsController@softDeleteRDV')->name('deleteRDV');
        Route::get('profile/edit-profile','ProfileController@index')->name('admin.profile.index');
        Route::post('profile/edit-profile', 'ProfileController@index')->name('admin.profile.index');
        Route::get('profile/change-password', 'ProfileController@password')->name('admin.profile.password');
        Route::post('profile/change-password', 'ProfileController@password')->name('admin.profile.password');
        // UploadController
        Route::post('upload', 'UploadController@index')->name('admin.upload');
    });

});
Route::resource('calendar', 'CalendarsController');
Route::group(['middleware' => 'auth'] , function() {
    //ProfileController
    Route::get('profile/edit-profile','ProfileController@index')->name('profile.index');
    Route::post('profile/edit-profile', 'ProfileController@index')->name('profile.index');
    Route::get('profile/change-password', 'ProfileController@password')->name('profile.password');
    Route::post('profile/change-password', 'ProfileController@password')->name('profile.password');
    // UploadController
    Route::post('upload', 'UploadController@index')->name('upload');
    //CalendarsController
   // Route::resource('calendar', 'CalendarsController');
   Route::post('proposerdv','CalendarsController@proposeRdv')->name('propose');
   Route::post('annulerRDV','CalendarsController@deleteRDV')->name('annulerRDV');
  // Route::get('proposerdv','CalendarsController@proposeRdv')->name('propose');
});

resources/views/includes/admin/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2020 <a href="https://adminlte.io">Addikah</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 0.0.1
    </div>
  </footer>
  

resources/views/includes/admin/header.blade.php
<?php

resources/views/includes/admin/navbar.blade.php
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
    </ul>
    <ul class="nav navbar-nav float-left">
      <li class="dropdown dropdown-user nav-item">
        <a class=" nav-link dropdown-user-link" href="#" data-toggle="dropdown">
        <i class="fas fa-th-large"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right">
           @if(session()->has('admin'))
            <a class="dropdown-item" href="{{ route('admin.profile.index') }}">
              <i class="ft-user"></i> Profil
            </a>
            <a class="dropdown-item" href="{{ route('admin.profile.password') }}">
              <i class="ft-lock"></i> Changer le mot de passe
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
              <i class="ft-power"></i> Se déconnecter
                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
            </a>
            @else
            <a class="dropdown-item" href="{{ route('profile.index') }}">
              <i class="ft-user"></i> Profil
            </a>
            <a class="dropdown-item" href="{{ route('profile.password') }}">
              <i class="ft-lock"></i> Changer le mot de passe
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
              <i class="ft-power"></i> Se déconnecter
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  @csrf
                </form>
            </a>
            @endif

          </div>
      </li>
   </ul>
  </nav>
  <!-- /.navbar -->

resources/views/includes/admin/page-header.blade.php
<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
          <i class="mdi mdi-home"></i>
        </span> {{$title ?? ''}}
    </h3>

    @if(isset($back_title))
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">
                    <h5 class="pg-title staff-title"><a href="{{ url($back_url) }}">{{ $back_title }}</a></h5>
                </li>
            </ul>
        </nav>
    @endif
</div>

resources/views/includes/admin/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{asset('dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          @if(session()->has('admin'))
          <li class="nav-item">
            <a href="{{route('admin.dashboard')}}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                  dashboard
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('clients.index')}}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                clients
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-table"></i>
              <p>
                En attente 
                <span class="badge badge-info right">6</span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="pages/widgets.html" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
              <p>
                Plages Horaires 
              </p>
            </a>
          </li>
          @endif
          <li class="nav-item">
            <a href="{{route('calendar.index')}}" class="nav-link">
              <i class="nav-icon far fa-calendar-alt"></i>
              <p>
                Calendrier
                <span class="badge badge-info right">2</span>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('admin.settings') }}" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                paramètres généraux 
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>